name: Check Code Formatting

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar clang-format
        run: sudo apt-get install clang-format

      - name: Verificar formatação do código
        run: |
          # Verificar todos os arquivos C e C++ no projeto
          git ls-files '*.c' '*.h' | while read file; do
            clang-format -i $file
            git diff --exit-code --quiet $file || (echo "$file precisa ser formatado!" && exit 1)
          done
